// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addContact = `-- name: AddContact :one
INSERT INTO contacts ( 
    user_id, 
    contact_user_id,  
    nickname
) VALUES (
    $1,
    $2,
    $3
) RETURNING id, user_id, contact_user_id, nickname, created_at
`

type AddContactParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	ContactUserID uuid.UUID   `json:"contact_user_id"`
	Nickname      pgtype.Text `json:"nickname"`
}

func (q *Queries) AddContact(ctx context.Context, arg AddContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, addContact, arg.UserID, arg.ContactUserID, arg.Nickname)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContactUserID,
		&i.Nickname,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :one
DELETE FROM contacts WHERE contact_user_id = $1 AND user_id = $2 RETURNING id, user_id, contact_user_id, nickname, created_at
`

type DeleteContactParams struct {
	ContactUserID uuid.UUID `json:"contact_user_id"`
	UserID        uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, deleteContact, arg.ContactUserID, arg.UserID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContactUserID,
		&i.Nickname,
		&i.CreatedAt,
	)
	return i, err
}

const getContactsByUserID = `-- name: GetContactsByUserID :many
SELECT 
    u.id, 
    u.username, 
    u.email, 
    u.created_at, 
    u.last_seen
FROM users u
INNER JOIN contacts c ON u.id = c.contact_user_id
WHERE c.user_id = $1
ORDER BY u.username ASC
`

type GetContactsByUserIDRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
}

func (q *Queries) GetContactsByUserID(ctx context.Context, userID uuid.UUID) ([]GetContactsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getContactsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactsByUserIDRow
	for rows.Next() {
		var i GetContactsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
