// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations(user1, user2) VALUES($1, $2) RETURNING id, user1, user2, created_at
`

type CreateConversationParams struct {
	User1 uuid.UUID `json:"user1"`
	User2 uuid.UUID `json:"user2"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.User1, arg.User2)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.User1,
		&i.User2,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :one
DELETE FROM conversations WHERE id = $1 RETURNING id, user1, user2, created_at
`

func (q *Queries) DeleteConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, deleteConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.User1,
		&i.User2,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByMembers = `-- name: GetConversationByMembers :one
SELECT id, user1, user2, created_at FROM conversations WHERE (user1 = $1 AND user2 = $2) OR (user1 = $2 AND user2 = $1)
`

type GetConversationByMembersParams struct {
	User1 uuid.UUID `json:"user1"`
	User2 uuid.UUID `json:"user2"`
}

func (q *Queries) GetConversationByMembers(ctx context.Context, arg GetConversationByMembersParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByMembers, arg.User1, arg.User2)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.User1,
		&i.User2,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationsByUserID = `-- name: GetConversationsByUserID :many
SELECT 
    conversations.id AS conversation_id,
    users.id, 
    users.last_seen, 
    users.username
FROM 
    conversations 
JOIN 
    users 
    ON users.id IN (conversations.user1, conversations.user2)
WHERE 
    -- 1. Ensure the conversation belongs to you
    (conversations.user1 = $1 OR conversations.user2 = $1)
    -- 2. CRITICAL: Filter out your own user record from the final list
    AND users.id != $1
`

type GetConversationsByUserIDRow struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	ID             uuid.UUID          `json:"id"`
	LastSeen       pgtype.Timestamptz `json:"last_seen"`
	Username       string             `json:"username"`
}

func (q *Queries) GetConversationsByUserID(ctx context.Context, user1 uuid.UUID) ([]GetConversationsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getConversationsByUserID, user1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationsByUserIDRow
	for rows.Next() {
		var i GetConversationsByUserIDRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ID,
			&i.LastSeen,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
