// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    sender_id, 
    conversation_id, 
    content
) VALUES (
    $1, 
    (
        SELECT id FROM conversations 
        WHERE (user1 = $1 AND user2 = $2) 
           OR (user1 = $2 AND user2 = $1)
        LIMIT 1
    ), 
    $3
)
RETURNING id, conversation_id, sender_id, content, is_read, created_at
`

type CreateMessageParams struct {
	SenderID uuid.UUID `json:"sender_id"`
	User2    uuid.UUID `json:"user2"`
	Content  string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.SenderID, arg.User2, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const getMessagesByConversationID = `-- name: GetMessagesByConversationID :many
SELECT id, conversation_id, sender_id, content, is_read, created_at
FROM messages
WHERE conversation_id = $1 
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type GetMessagesByConversationIDParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

// Ordered by created_at DESC for easy pagination
func (q *Queries) GetMessagesByConversationID(ctx context.Context, arg GetMessagesByConversationIDParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByConversationID, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesAsRead = `-- name: MarkMessagesAsRead :exec
UPDATE messages
SET is_read = TRUE
WHERE sender_id = $1 
  AND conversation_id = $2 
  AND is_read = FALSE
`

type MarkMessagesAsReadParams struct {
	SenderID       uuid.UUID `json:"sender_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
}

// Marks all messages sent FROM the contact TO the current user as read
func (q *Queries) MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error {
	_, err := q.db.Exec(ctx, markMessagesAsRead, arg.SenderID, arg.ConversationID)
	return err
}
