// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	ContactUserID uuid.UUID          `json:"contact_user_id"`
	Nickname      pgtype.Text        `json:"nickname"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID        uuid.UUID          `json:"id"`
	User1     uuid.UUID          `json:"user1"`
	User2     uuid.UUID          `json:"user2"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	SenderID       uuid.UUID          `json:"sender_id"`
	Content        string             `json:"content"`
	IsRead         pgtype.Bool        `json:"is_read"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"-"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastSeen     pgtype.Timestamptz `json:"last_seen"`
}
